// flow-typed signature: d4277ee6bc1daa47d4dcf2269c264103
// flow-typed version: <<STUB>>/gulp-sass-lint_v^1.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-sass-lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-sass-lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-sass-lint/tests/Gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-sass-lint/index' {
  declare module.exports: $Exports<'gulp-sass-lint'>;
}
declare module 'gulp-sass-lint/index.js' {
  declare module.exports: $Exports<'gulp-sass-lint'>;
}
declare module 'gulp-sass-lint/tests/Gulpfile.js' {
  declare module.exports: $Exports<'gulp-sass-lint/tests/Gulpfile'>;
}
