// flow-typed signature: 1e08d33d8f97bdd4926acffdc07f4ab4
// flow-typed version: <<STUB>>/gulp-size_v^2.1.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-size/index' {
  declare module.exports: $Exports<'gulp-size'>;
}
declare module 'gulp-size/index.js' {
  declare module.exports: $Exports<'gulp-size'>;
}
